DROP TABLE Sights;
CREATE TABLE Sights (
	id INT NOT NULL AUTO_INCREMENT,
	text TEXT NOT NULL,
	lat NUMERIC(8, 5) NOT NULL,
	lng NUMERIC(8, 5) NOT NULL,
	old_photo1 VARCHAR(50),
	old_photo2 VARCHAR(50),
	old_photo3 VARCHAR(50),
	photo VARCHAR(50),
	description TEXT,
	eng_description TEXT,
	PRIMARY KEY (id)
);
INSERT INTO Sights (text, lat, lng, old_photo1, old_photo2, old_photo3, photo, description, eng_description) VALUES (
	"Пионеры и ветераны на праздновании Дня Победы (на Центральной улице)",
	44.72178, 37.77258, "26.jpg", "", "", "",
	"Уже более семидесяти лет назад отгремели последние бои Второй Мировой войны, и мы живем под мирным небом в свободной стране. Каждый год наш город с большим размахом отмечает Всенародный праздник, день Победы. На этом кадре присутствующие чтят память доблестных воинов, отдавших свою жизнь за будущее своего родного города. Ежегодно 9 мая в Новороссийске проводится парад, посвященный этому знаменательному событию. В нем участвуют и живые свидетели тех событий, ведь каждый житель города-героя обязан знать и понимать, как дорого досталась жизнь и труд в свободной стране.",
	"More than seventy years ago, the last battles of World War II died down, and we live under a peaceful sky in a free country. Every year our city celebrates the national holiday, Victory Day, with great fanfare. In this picture, people present honor the memory of the courageous soldiers who gave their lives for the future of their hometown. Every year on 9th of May Novorossiysk holds a parade dedicated to this momentous event. Living witnesses of those events also take part in it, because every resident of the hero-city must know and understand how expensive life and labor were in a free country."
), (
	"Памятник затопленным кораблям под Новороссийском в 1918г",
	44.69186, 37.86683, "27.jpg", "", "", "",
	"Трагедии, о которой рассказывает памятник, в прошлом году исполнилось 104 года. Тогда, в непростом 1918-ом, Черноморский флот ушел из Севастополя в Новороссийск, и там по распоряжению В.И. Ленина часть кораблей была затоплена. В настоящее время этот памятник был усовершенствован, и на камне в виде стрелок-указателей были воссозданы из бронзы все названия затопленных кораблей. С изображением памятника, который является одним из символов ушедшего поколения, было выпущено множество коллекционной атрибутики: открытки, вымпелы, значки. Сегодня у памятника люди отдыхают, делая памятные фотографии, соприкасаясь с историей города, страны, поколения.",
	"The tragedy, about which the monument tells, turned 104 years old last year. Then, in the difficult year of 1918, the Black Sea Fleet left Sevastopol for Novorossiysk, and there, by order of Lenin, some of the ships were sunk. The monument has now been improved, and all the names of the sunken ships have been recreated in bronze on the stone in the form of arrows-pointers. With the image of the monument, which is one of the symbols of a bygone generation, a lot of collectible paraphernalia has been issued: postcards, pennants, badges. Today, people relax near the monument, taking commemorative photos, getting in touch with the history of the city, country and generation."
), (
	"Памятник «Неизвестному матросу»",
	44.7154, 37.78504, "01.jpg", "", "", "16.jpg",
	"Этот памятник расположился на Набережной Новороссийска. Он представляет собой высокий каменный постамент, на котором гордо стоит матрос с автоматом на плече и смотрит вдаль моря. Сама скульптура матроса вылита из бронзы. Общая высота монумента составляет 7 метров. Смотря на эту скульптурную композицию, невольно ощущаешь от нее мужество, мощь и стойкость. Автору очень хорошо удалось передать в фигуре матроса все эти качества, делая данный объект военного исторического наследия интересным как для местных жителей, так и для гостей Новороссийска.",
	"This monument is located on the Novorossiysk embankment. It is a high stone pedestal, on which a sailor with an automatic gun on his shoulder proudly stands and looks out to the sea. The sculpture itself is made of bronze. The total height of the monument is 7 meters. When you're looking at this sculptural composition, you can't help feeling the sculpture's courage, power and firmness. The author managed to convey all these qualities very well in the figure of a sailor, making this object of military historical heritage interesting for both locals and guests of Novorossiysk."
), (
	"Крейсер Кутузов, 1984 год 1 июля, Празднование 60-летия Морфлота СССР",
	44.72128, 37.78202, "02.jpg", "", "", "15.jpg",
	"Одной из достопримечательностей города-героя Новороссийска является артиллерийский крейсер «Михаил Кутузов», названный в честь великого полководца Михаила Илларионовича Кутузова. Разрабатывался с 1944 по 1945 годы. В прошлом крейсер был одной из сильнейших боевых единиц Черноморского флота, а в настоящее время является кораблем-музеем, где проводят экскурсии и рассказывают историю этого корабля. Крейсер оказался единственным сохранившимся кораблем проекта 68-бис. Благодаря стараниям ветеранов-кутузовцев корабль избежал участи продажи на слом. Он сохранен как символ эпохи, как памятник флоту и образец судостроения. Он все равно продолжает служить Родине, даже оставаясь на месте.",
	"One of the sights of the hero-city of Novorossiysk is the artillery cruiser Mikhail Kutuzov, named after the great commander Mikhail Illarionovich Kutuzov. It was developed from 1944 to 1945. In the past the cruiser was one of the strongest combat units of the Black Sea Fleet, and now is a ship-museum, where guided tours and history of the ship. The cruiser was the only remaining Project 68 bis ship. Thanks to the efforts of veteran Kutuzovs the ship avoided the fate of being sold for scrap. It has been preserved as a symbol of the era, as a monument to the Navy and an example of shipbuilding. It still continues to serve its homeland, even while remaining in place."
), (
	"Памятник «Взрыв» в посёлке Мысхако, Мемориальный комплекс «Долина смерти»",
	44.65698, 37.75415, "03.jpg", "", "", "14.jpg",
	"По всему миру установлены памятники, посвященные трагическим событиям времен Великой Отечественной войны. В Новороссийске, где шли ожесточенные бои, мемориалов памяти не сосчитать. Монумент «Взрыв» в Мысхако выполнен из осколков снарядов, авиабомб и мин. Он входит в состав мемориального комплекса «Долина смерти». Его вес составляет 1250 кг. Считается, что именно столько обрушили немецкие войска на каждого солдата, героически оборонявшего Малую землю. Надпись на памятнике гласит: «Помни, товарищ! 1250 килограммов смертоносного металла обрушил враг на каждого малоземельца в дни беспримерного подвига. Горели камни и земля плавилась. Они выстояли, за ними была Родина. Запомни это, современник, запомни и передай потомкам». Сам памятник был установлен в 1979 году.",
	"All over the world there are monuments dedicated to the tragic events of the Great Patriotic War. In Novorossiysk, where fierce battles took place, memorials can't be counted. Monument \"Explosion\" in Myskhako is made of fragments of shells, air bombs and mines. It is a part of the memorial complex \"Death Valley\". Its weight is 1250 kg. It is believed that this is how much the German troops dropped on each soldier, who heroically defended the Minor Land. The inscription on the monument reads: \"Remember, comrade! 1250 kilograms of lethal metal was dropped by the enemy on every citizen of Minor Land in the days of unprecedented feat. The stones were burning and the earth was melting. They stood their ground, their Motherland was behind them. Remember this, contemporary, remember it and pass it on to your descendants\". The monument itself was founded in 1979."
), (
	"1984 год 1 июля, Празднование 60-летия Морфлота СССР",
	44.72007, 37.78188, "28.jpg", "", "", "",
	"В последнее воскресенье июля по традиции отмечается день Военно-Морского Флота. 31 июля в Новороссийске основные мероприятия проводятся на Форумной площади. В них принимают участие военнослужащие Новороссийской военно-морской базы, военные оркестры из Новороссийска и Севастополя. По Форумной площади под звуки военного оркестра торжественным маршем проходят парадные подразделения военно-морского флота. Для гостей праздника проводились показательные выступления по рукопашному бою на суше, а также ряд показательных морских сражений: уничтожение морской мины, освобождение захваченного террористами судна, высадка десанта и встречный бой. Жители и гости могли увидеть в частности боевые образцы береговых ракетных комплексов «Бастион» и «Бал», а также систему радиоэлектронной разведки «Синтез». Вечером на Форумной площади состоялся праздничный фейерверк на Западном молу.",
	"On the last Sunday of July the Navy Day is traditionally celebrated. On July 31 in Novorossiysk the main events are held on Forum Square. They are attended by servicemen of the Novorossiysk Naval Base, military bands from Novorossiysk and Sevastopol. The parade units of the Navy march through Forum Square to the sound of the military band. For guests of the holiday were demonstrative performances in hand-to-hand combat on land, as well as a number of demonstrative sea battles: the destruction of a sea mine, the release of a ship captured by terrorists, landing and counterattack. Residents and guests could see, among other things, samples of the Bastion and Bal coastal missile systems and the Sintez electronic reconnaissance system. In the evening there was a festive fireworks display on the Western breakwater on Forum Square."
), (
	"70-тилетие революции 1905 года в Новороссийске",
	44.71801, 37.77704, "29.jpg", "", "", "",
	"7 ноября (25 октября по старому стилю) 1917 года в Петрограде под руководством Военно-революционного комитета Петроградского совета рабочих и солдатских депутатов началось вооруженное восстание рабочих, солдат городского гарнизона и матросов Балтийского флота. Был взят Зимний дворец, свергнуто и арестовано Временное правительство и провозглашена Советская власть. Начались выступления верных большевикам воинских частей и рабочей гвардии, которые методично брали под контроль основные объекты инфраструктуры столицы. День закончился по сигналу холостым выстрелом из крейсера «Авроры». С 1918 года день 7 ноября праздновался как Годовщина Великой Октябрьской социалистической революции. В 1927-1992 годах праздник отмечали 7 и 8 ноября, оба дня были выходными. С 1996 года он получил новое название - День согласия и примирения, а в 2004 году бал объявлен памятной датой - Днем Октябрьской революции 1917 года.",
	"On November 7 (October 25, O.S.) 1917 in Petrograd, under the leadership of the Military Revolutionary Committee of the Petrograd Soviet of Workers' and Soldiers' Deputies an armed uprising of workers, soldiers of the city garrison and sailors of the Baltic Fleet began. The Winter Palace was taken, the Provisional Government was overthrown and arrested, and Soviet power was proclaimed. The Bolshevik loyalist military units and workers' guards began to show up, methodically taking control of the capital's main infrastructure. The day ended on cue with a blank shot from the Aurora cruiser. Since 1918, November 7 was celebrated as the Anniversary of the Great October Socialist Revolution. In 1927-1992, the holiday was celebrated on November 7 and 8, both days off. In 1996 it was renamed the Day of Concord and Reconciliation, and in 2004 the ball was declared a memorable date - the Day of October Revolution in 1917."
), (
	"Памятник Ленину напротив Дворца Культуры, 1 мая 1926, авторы: скульптор В. В. Козлов, Л. А. Дитрих и К. А. Дитрих",
	44.72334, 37.7685, "04.jpg", "", "", "13.jpg",
	"После смерти В. И. Ленина в январе 1924 года жителям Новороссийска захотелось увековечить образ любимого Ильича. Тогда-то и родилась мысль создать памятник В. И. Ленину на средства портовиков, моряков, цементников, железнодорожников, комсомольских ячеек. По решению Черноморского окружного комитета РКП (б) от 9 апреля 1925 года вопрос о постройке памятника В.И. Ленину на средства трудящихся Новороссийска был вынесен для широкого обсуждения в городской газете «Красное Черноморье». Модель фигуры Владимира Ильича изготовили скульпторы В. Козлов и братья Дитрихи. Началось строительство, и 1 мая 1926 года состоялось его открытие. «Рабочие в один голос заявили: Ленину в Новороссийске на воротах в зарубежный мир должен быть памятник! Памятник вождю пролетариата соорудить возле Дворца труда, с тем, чтобы Ленин смотрел в открытое море - на мир!»",
	"After Lenin's death in January 1924, the residents of Novorossiysk wanted to immortalize the image of their beloved Ilyich. It was then that the idea was born to create a monument to V.I. Lenin at the expense of port workers, sailors, cement workers, railwaymen and Komsomol cells. In accordance with the decision of the Chernomorskiy district committee of the RCP (b) on April 9, 1925 the question about the construction of the monument to Lenin was submitted for a wide discussion in the city newspaper \"Krasnoe Chernomorye\" with the support of the workers of Novorossiysk. The model of the figure of Vladimir Lenin was made by sculptors V. Kozlov and brothers Dietrich. The construction began, and on May 1, 1926, its opening took place. \"The workers declared in one voice: there should be a monument to Lenin in Novorossiysk at the gateway to the foreign world! A monument to the leader of the proletariat should be built near the Palace of Labor, so that Lenin would look out into the open sea to the world!\""
), (
	"Памятник Ленину 1958г (на данный момент памятник Коминтерну)",
	44.73347, 37.78466, "30.jpg", "", "", "17.jpg",
	"",
	""
), (
	"Капсула с посланиями от советской молодежи 1967 года",
	44.71669, 37.77888, "05.jpg", "", "", "18.jpg",
	"Экспонаты из капсулы времени, пролежавшей на морском дне ровно полвека, представлены на новой выставке в Новороссийском историческом музее-заповеднике. Это послания, которые адресовали в 2017-й комсомольцы 60-х. 13 сентября 2017 года с шестиметровой глубины на входе в Цемесскую бухту, возле Суджукского маяка, подняли 15-тонную бетонную плиту с замурованной в нее капсулой. Внутри весточки из 1967 года. Их 144 - письма, магнитофонные записи, пластинки, фотографии, рисунки… И даже целый кинофильм - восемь бобин в жестяных банках, «Сказка о Мальчише-Кибальчише». Тексты были написаны карандашом либо тушью - считалось, что так они лучше сохранятся. Каждый конверт в целлофановой обертке. Все сохранилось в прекрасном состоянии.",
	"Exhibits from the time capsule, which had lain on the seabed for exactly half a century, are on display at a new exhibition at the Novorossiysk Historical Museum-Reserve. These are the messages that Komsomol members of the 60s addressed to 2017. On September 13, 2017, a 15-ton concrete slab with a capsule immured in it was lifted from a six-meter depth at the entrance to the Tsemesskaya Bay, near the Sudzhuk lighthouse. Inside the capsule there are messages from 1967. There are 144 of them: letters, tapes, records, photos, drawings... And even a whole film, eight reels in tin cans, \"The Tale of Boychish-Kibalchish\". The texts were written in pencil or in ink - it was thought that they would be better preserved that way. Each envelope was in a cellophane wrapper. Everything has been preserved in excellent condition."
), (
	"Центральный стадион, 13 августа - День Физкультурника (вторая суббота августа)",
	44.71385, 37.77936, "06.jpg", "", "", "19.jpg",
	"Центральный стадион имеет интересную и весьма продолжительную историю. Он начал строиться в 1929 году. На начальном этапе там проводились субботники и затем уже подключились профессиональные строители. Благодаря сплоченному труду стадион был готов в 1930 году и получил название «Динамо». К сожалению, результаты войны уничтожили почти все в городе, в том числе и этот стадион. С 1953 по 1955 годы стадион отстроили вновь и он получил название «Труд». Сооружение представляло собой футбольное поле с одной высокой трибуной для руководства коммунистической партии и предприятий. Через 3 года успели закончить восточную трибуну. В 1961 году построили западную и южную трибуны. В результате, теперь основной стадион города Новороссийска может вместить в себя 12910 человек. Комплекс также имеет здесь офис футбольного клуба «Черноморец» и отель, в 1999 году был уложен газон.",
	"The Central Stadium has an interesting and very long history. It began to be built in 1929. At the initial stage there were subbotniks and then professional builders joined in. Thanks to their joint efforts, the stadium was ready in 1930 and was called \"Dynamo\". Unfortunately, the results of the war destroyed almost everything in the city, including this stadium. From 1953 to 1955 the stadium was rebuilt again and was called \"Trud\". The building was a soccer field with one high stand for the leaders of the Communist Party and enterprises. In 3 years the eastern stand had been finished. In 1961 the west and south stands were built. As a result, now the main stadium of the city of Novorossiysk can accommodate 12910 people. The complex also has here the office of soccer club \"Chernomorets\" and a hotel, in 1999 the lawn was laid."
), (
	"Мемориальный комплекс «Площадь героев» (реконструкция 1974 г.), Караульные на посту у вечного огня",
	44.72004, 37.7762, "07.jpg", "31.jpg", "", "20.jpg",
	"Мемориальный комплекс «Площадь Героев» находится в самом центре города Новороссийска: в квадрате улиц Мира, Рубина, Советов, пер. Мичурина. «Площадь Героев» представлена зелеными аллеями с многолетними деревьями, цветочными клумбами. Там можно прогуляться в тени высоких деревьев и насладиться спокойной атмосферой. На одной из аллей с 1965 года городами-побратимами принято высаживать «Дерево дружбы». На территории комплекса находится вечный огонь, памятники и монументы, посвященные воинам Великой Отечественной войны. С этого монумента началась история города-героя. Именно отсюда он начал строиться и развиваться. В 50-х годах архитекторы создали и воплотили в жизнь проект по застройке мемориального ансамбля. С 1958 на площади горит Огонь вечной славы, а с 1960г. Он ежечасно сопровождается музыкальным произведением Шостаковича «Новороссийские куранты».",
	"The memorial complex \"Heroes' Square\" is located in the center of Novorossiysk: in the square of Mir, Rubin, Sovetov and Michurin streets. \"Heroes' Square\" is represented by green alleys with perennial trees, flowerbeds. There you can stroll in the shade of tall trees and enjoy the quiet atmosphere. On one of the alleys from 1965 twin cities adopted to plant \"Friendship Tree\". There is an eternal flame, monuments and monuments dedicated to the soldiers of the Great Patriotic War. The history of the hero-city began with this monument. This is where it began to be built and developed. In the 50's architects created and implemented a project to build the memorial ensemble. Since 1958 on the square the Flame of eternal glory burns, and since 1960 it is accompanied hourly by the musical composition of Shostakovich \"Novorossiysk chimes\"."
), (
	"Заложение плиты (надпись неразборчива)",
	44.65686, 37.7538, "32.jpg", "", "", "",
	"",
	""
), (
	"Арка, сооруженная в честь миллионной бочки цемента в 1920-е гг.",
	44.73615, 37.80129, "08.jpg", "", "", "21.jpg",
	"В Восточном районе Новороссийска на Сухумском шоссе расположена одна из городских достопримечательностей - арка, посвященная выпуску миллионной бочки цемента, выпущенной заводом «Пролетарий» после окончания Гражданской войны. Арка была сооружена 14 сентября 1925 года. На одной ее стороне написано: «Пролетарии всех стран соединяйтесь», на другой готическим шрифтом: «Мы новый мир построим». Ранее под аркой проходило старое «русло» Сухумского шоссе. Сейчас направление дороги, соединявшей юг и центр Черноморского побережья немного сместили.",
	"In the eastern district of Novorossiysk on Sukhumskoye Shosse is one of the city's landmarks - an arch dedicated to the production of a million barrels of cement produced by the Proletarian plant after the Civil War. The arch was erected on September 14, 1925. On one side of it is written: \"Proletarians of all countries unite,\" on the other - in gothic letters: \"We will build a new world\". Earlier under the arch was the old \"riverbed\" of Sukhumi highway. Now the direction of the road connecting the south and center of the Black Sea coast is slightly shifted."
), (
	"Памятник «Погибшим на пароходе Адм. Нахимов»",
	44.62999, 37.90735, "09.jpg", "", "", "22.jpg",
	"В поселке Кабардинка, в районе комплекса «Надежда» на мысе Дооб установлен памятник пароходу «Адмирал Нахимов», который затонул в 15 км от Новороссийска в 1986 году. В 1987 в годовщину трагедии на мысе был установлен памятник погибшим в результате этой страшной аварии. Памятник выглядит как композиция из металлических труб разной высоты, символизирующих оборванные человеческие жизни. В нижней части - разорванный бетонный круг в виде волны, захлестнувшей пароход. В центре, на трубах, укреплены часы, которые были подняты со дна моря - с борта теплохода. Они показывают 23.20 - время трагедии.",
	"In the village of Kabardinka, near the complex \"Hope\" on Cape Doob is a monument to the steamship \"Admiral Nakhimov\", which sank 15 km from Novorossiysk in 1986. In 1987 on the anniversary of the tragedy a monument to the victims of that terrible accident was erected on the cape. The monument looks like a composition of metal pipes of different height, symbolizing the broken human lives. In the lower part there is a broken concrete circle in the form of a wave that swept the ship. In the center, on the tubes, there is a clock, which was raised from the bottom of the sea - from the ship. It shows 23.20, the time of the tragedy."
), (
	"Площадь Свободы",
	44.72137, 37.77211, "33.jpg", "", "", "",
	"Прогуливаясь по центральной парковой аллее на пути встречается площадь Свободы. Это небольшая площадь, образованная на пересечении улиц Свободы и Советов. В центре пересечения на постаменте установлен памятник «Воинам-защитникам» города Новороссийска 1942-1943 гг. - дань памяти воевавшим в ВОВ. Представляет собой композицию из трех людей - мужчины с автоматом, мужчины со знаменем и женщины-медсестры. Барельефы, находящиеся по бокам от основной композиции, запечатлели высадку десанта на Малую Землю. Дата открытия памятника - 1961 год, скульпторы - Н. Тимошин, И. Шмагун, архитектор - К. Михайлов. Недалеко от площади в парковой аллее есть участок, где молодожены увековечивают свои чувства в виде тротуарной плитки со своими именами и памятной датой свадьбы.",
	"Walking along the central park alley on the way you meet Freedom Square. This is a small square, formed at the intersection of Svobody and Sovetov streets. In the center of the intersection on the pedestal there is a monument \"Warriors-defenders\" of Novorossiysk 1942-1943. It is a composition of three people - a man with a gun, a man with a banner and a woman-nurse. Bas-reliefs, located on the sides of the main composition, depict the landing of troops on the Small Earth. The monument was unveiled in 1961 by sculptors N. Timoshin and I. Shmagun, architect K. Mikhailov. Not far from the square in the park alley there is an area where the newlyweds immortalize their feelings in the form of paving tiles with their names and a memorable wedding date."
), (
	"Набережная в советское время",
	44.70864, 37.78877, "10.jpg", "", "", "23.jpg",
	"Набережная адмирала Серебрякова протянулась вдоль западного берега Цемесской бухты в центральной части города. Это одно из любимейших мест жителей и гостей города-героя. Набережная берет свое начало на пересечении с улицей Новороссийской республики и заканчивается пересечением с улицей Суворовской. Набережная Адмирала Серебрякова в Новороссийске располагает множеством памятников, посвященных историческим событиям и личностям города. Она является популярным местом отдыха и прогулок не только туристов, но и местных жителей. Новороссийская Набережная предназначена для пеших прогулок, катания на велосипедах и роликах. Дорожки выложены брусчаткой. По ее краям разбиты аккуратные газоны, на клумбах высажены цветы.",
	"Admiral Serebryakov embankment stretches along the western shore of Tsemesskaya Bay in the central part of the city. It is one of the favorite places of residents and guests of the hero-city. The embankment begins at the intersection with Novorossiyskaya Street and ends at the intersection with Suvorovskaya Street. Admiral Serebryakov embankment in Novorossiysk has many monuments dedicated to historical events and personalities of the city. It is a popular place of rest and walks not only for tourists, but also for locals. Novorossiysk embankment is designed for walking, cycling and rollerblading. The paths are lined with paving stones. Its edges are laid out neat lawns, flowers are planted in flowerbeds."
), (
	"Вид на 1 корпус НКСЭ",
	44.72052, 37.77493, "11.jpg", "", "", "24.jpg",
	"История колледжа начинается с создания в городе двух учебных заведений - силикатного техникума и коммунально-строительного техникума, которые были открыты по решению строительных объединений ВСНХ РСФСР. За это время для предприятий и учреждений Краснодарского края оба учебных учреждения подготовили тысячи выпускников, многие из них стали ведущими специалистами в своих отраслях, руководителями предприятий города и страны. В 2006 году было сформировано одно учебное заведение - Новороссийский колледж строительства и экономики. Сегодня колледж играет значимую роль в подготовке высококвалифицированных специалистов для строительной отрасли, ЖКХ, экономики и сферы услуг Краснодарского края. В колледже сложился профессионально компетентный и работоспособный педагогический коллектив. Более половины преподавателей имеют высшую квалификационную категорию, что определило достижения колледжа за многие годы.",
	"The history of the college begins with the creation of two educational institutions in the city - silicate technical school and communal-building technical school, which were opened by the decision of the construction associations VSNKh RSFSR. During this time for the enterprises and institutions of the Krasnodar Territory, both educational institutions have prepared thousands of graduates, many of them have become leading experts in their fields, heads of enterprises of the city and the country. In 2006, there was formed a single educational institution - Novorossiysk College of Construction and Economics. Today the college plays an important role in training highly qualified specialists for the construction industry, housing and communal services, economy and the sphere of services of Krasnodar Territory. The college has a professionally competent and hard-working teaching staff. More than half of the teachers have the highest qualification category, which has determined the college's achievements over the years."
), (
	"Здание центральной почты Новороссийска (строительство)",
	44.72123, 37.77362, "12.jpg", "", "", "25.jpg",
	"10 июля отмечается День российской почты - профессиональный праздник работников почтовой связи. Почта Новороссийска - это место, которое обслуживает миллионы людей. В нем трудятся сотни работников. Компания постоянно развивается, внедряет современные технологии, расширяет перечень предоставляемых услуг. Но, как и везде, важнейшими в отрасли всегда были и остаются люди. В прошлом году сотрудниками почты Новороссийска было обработано и доставлено около 100 миллионов писем, посылок и иных видов корреспонденции.",
	"July 10 is the Day of Russian Post, the professional holiday of postal workers. Novorossiysk Post is a place that serves millions of people. It employs hundreds of workers. The company is constantly developing, introducing modern technology, expanding the list of services provided. But, as everywhere else, the most important in the industry have always been and remain people. Last year Novorossiysk Post employees processed and delivered about 100 million letters, parcels and other types of correspondence."
), (
	"Малая Земля",
	44.68847, 37.79758, "34.jpg", "35.jpg", "36.jpg", "37.jpg",
	"Новороссийск. Плацдарм в Новороссийске, образовавшийся 4 февраля 1943 года в результате десантной операции 18-й десантной армии Черноморской группы войск и Черноморского флота, предпринятой с целью освобождения города.",
	"Novorossiysk. A bridgehead in Novorossiysk, formed on February 4, 1943 as a result of an amphibious operation of the 18th Amphibious Army of the Black Sea Group of Troops and the Black Sea Fleet, undertaken to liberate the city."
), (
	"Стелла",
	44.68644, 37.79493, "39.jpg", "", "", "38.jpg",
	"Установлена в честь героического отряда десантников под командованием майора Куникова Цезаря Львовича и в память о героических боях на Малой Земле.",
	"It was installed in honor of the heroic detachment of paratroopers under the command of Major Kunikov Caesar Lvovich and in memory of the heroic battles on Malaya Zemlya."
);
